export { default as Figure } from './Figure'
export { default as Header } from './Header'
export { default as Notification } from './Notification'
export { default as Popup } from './Popup'
export { default as Word } from './Word'
export { default as WrongLetters } from './WrongLetters'
